"""Initial migration

Revision ID: 728998e204fa
Revises: 
Create Date: 2026-02-12 05:57:06.740363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '728998e204fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_level', mysql.ENUM('super', 'regular'), server_default=sa.text("'regular'"), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('allergies',
    sa.Column('allergy_id', sa.Integer(), nullable=False),
    sa.Column('allergy_name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('allergy_type', mysql.ENUM('medication', 'food', 'environmental', 'other'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('allergy_id')
    )
    op.create_table('appointment_followups',
    sa.Column('followup_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('followup_status', mysql.ENUM('pending', 'contacted', 'resolved', 'ignored'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('followup_id')
    )
    op.create_table('appointment_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('default_duration_minutes', sa.Integer(), server_default=sa.text("'30'"), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('appointment_type_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.ENUM('scheduled', 'completed', 'canceled', 'no-show', 'rescheduled'), server_default=sa.text("'scheduled'"), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('reason', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('start_treatment_time', sa.DateTime(), nullable=True),
    sa.Column('end_treatment_time', sa.DateTime(), nullable=True),
    sa.Column('doctor_location_id', sa.Integer(), nullable=True, comment='FK to doctor_locations.doctor_location_id'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('target_table', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('target_record_id', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('action_details', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip_address', sa.String(length=45, collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', mysql.ENUM('doctor', 'patient', 'system'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('has_attachment', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'closed', 'pending'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('subject', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('conditions',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('icd_code', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('urgency_level', mysql.ENUM('low', 'medium', 'high', 'emergency'), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('condition_type', mysql.ENUM('common', 'rare', 'chronic', 'acute'), nullable=True),
    sa.Column('age_relevance', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('gender_relevance', mysql.ENUM('all', 'male', 'female'), server_default=sa.text("'all'"), nullable=True),
    sa.Column('specialist_type', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('self_treatable', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('typical_duration', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('educational_content', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('overview', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('regular_symptoms_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('emergency_symptoms_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('risk_factors_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('treatment_protocols_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('symptoms_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('causes_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('complications_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('testing_details', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('diagnosis_details', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('condition_image_filename', sa.String(length=500, collation='utf8mb4_bin'), nullable=True),
    sa.Column('condition_video_filename', sa.String(length=500, collation='utf8mb4_bin'), nullable=True),
    sa.Column('testing_type_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis_type_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('image_filename', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis_date', sa.Date(), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('diagnosis_name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('diagnosis_type', mysql.ENUM('preliminary', 'differential', 'final', 'working'), server_default=sa.text("'final'"), nullable=True),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('treatment_details', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('treatment_plan', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('follow_up_required', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('follow_up_type', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('severity', mysql.ENUM('mild', 'moderate', 'severe', 'critical', 'unknown'), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('prognosis', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_chronic', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('is_resolved', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_table('diagnosis_types',
    sa.Column('diagnosis_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('diagnosis_type_id')
    )
    op.create_table('diet_plan_food_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=100, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('serving_size', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_grams', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('carbs_grams', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('fat_grams', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('alternatives', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('diet_plan_meals',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=100, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('meal_type', mysql.ENUM('breakfast', 'lunch', 'dinner', 'snack', 'other'), nullable=False),
    sa.Column('protein_grams', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('description', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('carbs_grams', sa.Integer(), nullable=True),
    sa.Column('fat_grams', sa.Integer(), nullable=True),
    sa.Column('fiber_grams', sa.Integer(), nullable=True),
    sa.Column('sodium_mg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('diet_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('plan_type', mysql.ENUM('standard', 'custom', 'medical', 'weight_loss', 'weight_gain', 'maintenance'), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_grams', sa.Integer(), nullable=True),
    sa.Column('carbs_grams', sa.Integer(), nullable=True),
    sa.Column('fat_grams', sa.Integer(), nullable=True),
    sa.Column('fiber_grams', sa.Integer(), nullable=True),
    sa.Column('sodium_mg', sa.Integer(), nullable=True),
    sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('target_conditions', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('doctor_availability_overrides',
    sa.Column('override_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_location_id', sa.Integer(), nullable=True),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_unavailable', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('reason', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_table('doctor_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('document_type', mysql.ENUM('license', 'certification', 'identity', 'education', 'other'), nullable=False),
    sa.Column('file_name', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('file_path', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('doctor_location_availability',
    sa.Column('location_availability_id', sa.Integer(), nullable=False),
    sa.Column('doctor_location_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', mysql.TINYINT(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('location_availability_id')
    )
    op.create_table('doctor_location_daily_caps',
    sa.Column('cap_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_location_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', mysql.TINYINT(), nullable=False),
    sa.Column('max_appointments', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('cap_id')
    )
    op.create_table('doctor_locations',
    sa.Column('doctor_location_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('address', sa.Text(collation='utf8mb4_bin'), nullable=False),
    sa.Column('city', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('state', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('zip_code', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('country', sa.String(length=50, collation='utf8mb4_bin'), server_default=sa.text("'United States'"), nullable=True),
    sa.Column('phone_number', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('google_maps_link', sa.String(length=1024, collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('doctor_location_id')
    )
    op.create_table('doctor_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('action', mysql.ENUM('viewed', 'approved', 'rejected', 'info_requested'), nullable=False),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('doctors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('license_state', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('npi_number', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('medical_school', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('certifications', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('accepting_new_patients', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.Column('biography', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('clinic_address', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('verification_status', mysql.ENUM('pending', 'approved', 'rejected', 'pending_info'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('food_item_library',
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('serving_size', sa.String(length=100, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_grams', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('carbs_grams', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fat_grams', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fiber_grams', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('food_item_id')
    )
    op.create_table('insurance_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_attachments',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('file_type', sa.String(length=100, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('patient_allergies',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('allergy_id', sa.Integer(), nullable=False),
    sa.Column('severity', mysql.ENUM('mild', 'moderate', 'severe', 'unknown'), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('reaction_description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('diagnosed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', 'allergy_id')
    )
    op.create_table('patient_medical_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('document_type', sa.String(length=100, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('report_format', sa.String(length=10, collation='utf8mb4_general_ci'), server_default=sa.text("'json'"), nullable=True),
    sa.Column('file_path', sa.String(length=512, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('submission_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('patient_symptoms',
    sa.Column('patient_symptom_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('duration', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('frequency', mysql.ENUM('constant', 'intermittent', 'occasional', 'rare'), nullable=True),
    sa.Column('triggers', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('alleviating_factors', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('worsening_factors', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('patient_symptom_id')
    )
    op.create_table('patient_vaccinations',
    sa.Column('patient_vaccination_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('administration_date', sa.Date(), nullable=False),
    sa.Column('dose_number', sa.String(length=20, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('lot_number', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('administered_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('patient_vaccination_id')
    )
    op.create_table('patients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', mysql.ENUM('male', 'female', 'other', 'prefer_not_to_say', 'unknown'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('blood_type', mysql.ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown'), server_default=sa.text("'Unknown'"), nullable=True),
    sa.Column('height_cm', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('insurance_provider_id', sa.Integer(), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('insurance_group_number', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('insurance_expiration', sa.Date(), nullable=True),
    sa.Column('marital_status', mysql.ENUM('single', 'married', 'divorced', 'widowed', 'separated', 'other'), nullable=True),
    sa.Column('occupation', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pending_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('first_name', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('last_name', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('username', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('phone', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('country', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('user_type_requested', mysql.ENUM('doctor'), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('license_number', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('license_state', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'approved_user_created', 'rejected'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('date_processed', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('specialization_id')
    )
    op.create_table('symptoms',
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('symptom_name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('body_area', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('icd_code', sa.String(length=20, collation='utf8mb4_bin'), nullable=True),
    sa.Column('common_causes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('severity_scale', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('symptom_category', mysql.ENUM('common', 'rare', 'emergency', 'chronic'), nullable=True),
    sa.Column('age_relevance', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('gender_relevance', mysql.ENUM('all', 'male', 'female'), server_default=sa.text("'all'"), nullable=True),
    sa.Column('question_text', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('follow_up_questions', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('symptom_id')
    )
    op.create_table('testing_types',
    sa.Column('testing_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('testing_type_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('email', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('password', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('first_name', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('last_name', sa.String(length=50, collation='utf8mb4_bin'), nullable=False),
    sa.Column('user_type', mysql.ENUM('patient', 'doctor', 'admin'), nullable=False),
    sa.Column('phone', sa.String(length=30, collation='utf8mb4_bin'), nullable=True),
    sa.Column('country', sa.String(length=50, collation='utf8mb4_bin'), server_default=sa.text("'United States'"), nullable=True),
    sa.Column('profile_picture', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('account_status', mysql.ENUM('active', 'inactive', 'suspended', 'pending'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vaccine_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('target_group', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('image_filename', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('vaccines',
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('abbreviation', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('diseases_prevented', sa.Text(collation='utf8mb4_bin'), nullable=False),
    sa.Column('recommended_for', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('benefits', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('timing_schedule', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('number_of_doses', sa.String(length=50, collation='utf8mb4_bin'), nullable=True),
    sa.Column('booster_information', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('vaccine_type', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('administration_route', sa.String(length=100, collation='utf8mb4_bin'), nullable=True),
    sa.Column('common_side_effects', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('contraindications_precautions', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('storage_requirements', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('manufacturer', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('notes', sa.Text(collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('vaccine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    op.drop_table('vaccine_categories')
    op.drop_table('users')
    op.drop_table('testing_types')
    op.drop_table('symptoms')
    op.drop_table('specializations')
    op.drop_table('pending_registrations')
    op.drop_table('patients')
    op.drop_table('patient_vaccinations')
    op.drop_table('patient_symptoms')
    op.drop_table('patient_medical_reports')
    op.drop_table('patient_allergies')
    op.drop_table('message_attachments')
    op.drop_table('insurance_providers')
    op.drop_table('food_item_library')
    op.drop_table('doctors')
    op.drop_table('doctor_reviews')
    op.drop_table('doctor_locations')
    op.drop_table('doctor_location_daily_caps')
    op.drop_table('doctor_location_availability')
    op.drop_table('doctor_documents')
    op.drop_table('doctor_availability_overrides')
    op.drop_table('diet_plans')
    op.drop_table('diet_plan_meals')
    op.drop_table('diet_plan_food_items')
    op.drop_table('diagnosis_types')
    op.drop_table('diagnoses')
    op.drop_table('departments')
    op.drop_table('conditions')
    op.drop_table('chats')
    op.drop_table('chat_messages')
    op.drop_table('audit_log')
    op.drop_table('appointments')
    op.drop_table('appointment_types')
    op.drop_table('appointment_followups')
    op.drop_table('allergies')
    op.drop_table('admins')
    # ### end Alembic commands ###
