"""updated the BL added BL for users and docs and admins and patients and admins and also handled the foriegn keys for the classes

Revision ID: db170d5e4868
Revises: 728998e204fa
Create Date: 2026-02-12 06:28:55.604709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db170d5e4868'
down_revision: Union[str, Sequence[str], None] = '728998e204fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admins', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['user_id'])
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    # ### end Alembic commands ###
